Front end/browse vehicles
NathanGrenier/SOEN-341 pull request #184
Opened 2024-03-11 00:34 UTC by JeremyCrete

### 🛠 Proposed Changes:

Created browse vehicle page, added filtering options and connected the cars to the database

### 📝 Details:

-Browse vehicle page is user friendly and allows you to view all relevant information about the vehicles

### 🔗 Related Issue(s):

- Resolves #99 #100 #102 #101 #103 #105

2024-03-11 01:43 UTC, NathanGrenier requested changes

2024-03-11 01:43 UTC, NathanGrenier commented on .prettierignore
> +hooks.server.ts
Why is this file being ignored when it comes to formatting?

2024-03-11 01:43 UTC, NathanGrenier commented on src/lib/controllers/carController.ts
Having a bunch of functions described in a file is greater if they obfuscate complexity. 

However, I think it's fine if you just use the prisma library directly in the page.server files if these functions are only being used once in a single place.

2024-03-11 01:43 UTC, NathanGrenier commented on src/routes/+layout.svelte
> +    background-color: #08417a;
Make sure to try and use the skeleton colors and fonts wherever possible.

Replace this with one of the variants or the predefined tailwind color classes.

2024-03-11 01:43 UTC, NathanGrenier commented on src/routes/browse-vehicles/+page.svelte
Try an use the components provided by skeleton wherever possible. It'll make the site look more consistent.

2024-03-11 01:43 UTC, NathanGrenier commented on src/routes/browse-vehicles/+page.svelte
> +          <img src={"link"} alt={"image of a car"} />
Replace `"link"` with an actual link

2024-03-12 01:36 UTC, CarciDev approved these changes

2024-03-12 01:52 UTC, merged